# Generated by Django 5.2.8 on 2025-11-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
